spring.application.name=demo
# spring.datasource.url=jdbc:postgresql://db:5432/somedb
spring.datasource.url=jdbc:postgresql://localhost:5432/somedb
spring.datasource.username=postgres
spring.datasource.password=somesecret
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
