spring.application.name=demo
spring.datasource.url=jdbc:postgresql://db:5432/example
# spring.datasource.url=jdbc:postgresql://localhost:5432/example
spring.datasource.username=user
spring.datasource.password=secret
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
